// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbwWW-H5YttS8oB8dFhErv-0C-l_N8eQM',
    appId: '1:119258602269:web:bed2567bc78f56c0e55ff4',
    messagingSenderId: '119258602269',
    projectId: 'baiscdiet',
    authDomain: 'baiscdiet.firebaseapp.com',
    storageBucket: 'baiscdiet.firebasestorage.app',
    measurementId: 'G-WTEJRDLQTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPF-sEKupu3SRO2iPZR8Ie1aWBcZw4Zfo',
    appId: '1:119258602269:android:de37b05b5201277fe55ff4',
    messagingSenderId: '119258602269',
    projectId: 'baiscdiet',
    storageBucket: 'baiscdiet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Gc57ri2vnDvmB7ZpMlAQA7dxmP7Jzqg',
    appId: '1:119258602269:ios:6a9bbe7a67fa9b53e55ff4',
    messagingSenderId: '119258602269',
    projectId: 'baiscdiet',
    storageBucket: 'baiscdiet.firebasestorage.app',
    iosBundleId: 'com.example.basicDiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Gc57ri2vnDvmB7ZpMlAQA7dxmP7Jzqg',
    appId: '1:119258602269:ios:6a9bbe7a67fa9b53e55ff4',
    messagingSenderId: '119258602269',
    projectId: 'baiscdiet',
    storageBucket: 'baiscdiet.firebasestorage.app',
    iosBundleId: 'com.example.basicDiet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbwWW-H5YttS8oB8dFhErv-0C-l_N8eQM',
    appId: '1:119258602269:web:cd0b9cfbcc6ea36ae55ff4',
    messagingSenderId: '119258602269',
    projectId: 'baiscdiet',
    authDomain: 'baiscdiet.firebaseapp.com',
    storageBucket: 'baiscdiet.firebasestorage.app',
    measurementId: 'G-MQLD1VQSXF',
  );
}
